### PR TITLE
GHC-9.2, Haskell-CI

### PR DESCRIPTION
**Pull request by andreasabel**
Allow compilation with GHC 9.2.
No code changes, bounds relaxation only.  
No need to re-release `hackage-security`. ~~(But maybe some other packages have commits already that are needed for GHC 9.0/9.2?)~~

* Bump upper bounds:
  - `base`
  - `optparse-applicative`
  - `http-client`
  - `time`

* Not bumped: `transformers` (await `mtl-2.3` release).

* Generate haskell-ci.yml workflow so that all GHC versions advertised in `tested-with` are actually tested.

* Restrict existing multi-OS CI to last 3 GHC versions (8.10, 9.0, 9.2).

Revisions to do:
- [x] hackage-security-0.6.2.1 (just released for GHC 9)
- [x] hackage-security-HTTP-0.1.1.1: compiles with
  ```
  cabal build --allow-newer=base
  ```

Releases to do:
- [ ] hackage-repo-tool-0.1.1.2: compiles with
  ```
  cabal build --allow-newer=hackage-security:base --allow-newer=hackage-repo-tool:base --allow-newer=Cabal
  ```
  __Needs release__ because of added flag `Cabal-syntax`.

### CODE REVIEW

**Comment by andreasabel** [comment]
@Mikolaj : CI passes.  Would you like me to do the revisions on hackage that are contained in this PR? 
This would bring the hackage-security family to GHC 9.2.

**Comment by andreasabel** [comment]
I revised what was possible, but `hackage-repo-tool` needs a release.  ("Needs" in the sense that whenever someone needs it.)

**Comment by Mikolaj** [comment]
Got it. Thank you. Merging.

**Comment by Mikolaj** [comment]
BTW, what do the revision fields do? What's their purpose? I think I removed one somewhere recently, but perhaps I should have something first?

**Comment by Mikolaj** [comment]
It turns out we need `hackage-repo-tool` for our cabal CI, so I'm now releasing it.

**Comment by andreasabel** [comment]
> BTW, what do the revision fields do? What's their purpose? I think I removed one somewhere recently, but perhaps I should have something first?

Sorry, @Mikolaj, never saw this question.  The `x-revision` determines the revision.  It needs to be set correctly when uploading a revision via the hackage-server API, e.g. via `hackage-cli`.  If you revise manually via the web interface, Hackage sets it correctly for you.  
(Revised packages retrieved with `cabal get` will all have this `x-revision` field.)

**Comment by Mikolaj** [comment]
Got it. thank you.

**Pull request merged**
