### PR TITLE
Bump base, containers, filepath, network, time, zlib, CI for GHC 9.10

### PR DESCRIPTION
**Pull request by andreasabel**
I tested building with `network-3.2.0.0` locally.

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
Wow, GHC 9.10, great!

**Comment by andreasabel** [comment]
@Mikolaj: I made revision 1 of `hackage-security-0.6.2.6`: https://hackage.haskell.org/package/hackage-security-0.6.2.6/revisions/
To release `hackage-repo-tool` and `hackage-security-HTTP`, I lack the upload rights on Hackage.
I pushed commits here to bump their version, so you can release from this PR. (And then add tags.)

**Comment by Mikolaj** [comment]
@andreasabel: great job! 

> To release hackage-repo-tool and hackage-security-HTTP, I lack the upload rights on Hackage.

That was an oversight. Now you have the upload rights.

**Comment by andreasabel** [comment]
Done and tagged.

**Pull request merged**
