### PR TITLE
Use file instead of dir locking #187

### PR DESCRIPTION
**Pull request by snoyberg**
This commit simply imports the code from the filelock package verbatim into a subdirectory, filelock. Depending on filelock as an external package instead would be more straightforward, but I'm not sure what the rules for external dependencies are here.

### CODE REVIEW

**Comment by snoyberg** [comment]
Looks like this would address #126 as well.

**Comment by hvr** [comment]
*Sigh* If we wanted to use the `filelock` package, we would simply depend on it...

**Comment by snoyberg** [comment]
Unless you edited a comment to say something different than it did originally, I haven't seen any comment stating that filelock was considered and excluded, much less a reason given for this decision. I'd appreciate if you could point to where this comment was made.

**Comment by 23Skidoo** [comment]
Even if a better solution is coming, can't we merge this PR for now as a stopgap and then drop the `filelock` dep from the next release?

**Comment by dcoutts** [comment]
@hvr I didn't see what the problems with filelock are? Can you point it out? On the face of it I'm inclined to agree that we take the patch and use filelock, and we can of course still make further changes and improvements later.

**Comment by hvr** [comment]
Fair enough, let's merge this as a a temporary stopgap solution for now.

**Comment by dcoutts** [comment]
Ok, so the issue is the unix `flock()` vs `fnctl()`. Locking semantics and impls on Unix are a mess. http://0pointer.de/blog/projects/locking.html

`fnctl()` is more portable but has pretty funky semantics, whereas `flock` is less portable but has saner semantics. It's also worth noting that the base 4.10 and above has partial support for file locking on windows and unix. We implemented this for the locking support in ghc & ghc-pkg of the package db. On unix the `Handle` locking is via `flock`, but it explicitly throws `FileLockingNotImplemented` for platforms that do not support `flock` so one has to pick a fallback in those cases.

**Comment by dcoutts** [comment]
@snoyberg thanks for poking through the issues that this resolves.

**Comment by snoyberg** [comment]
No problem @dcoutts :)

**Pull request merged**
