### PR TITLE
fix spelling errors

### PR DESCRIPTION
**Pull request by askeblad**
hackage-security/src/Hackage/Security/Client/Repository.hs
hackage-security/src/Hackage/Security/Client/Repository/HttpLib.hs
hackage-security/src/Hackage/Security/Key.hs

@Mikolaj

as per https://github.com/haskell/hackage-security/pull/269#issuecomment-1067411773
\+ a couple more errors

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
LGTM. Thank you.

**Comment by Mikolaj** [comment]
In this repo 1 review is enough. Please feel free to merge.

**Comment by askeblad** [comment]
> Please feel free to merge.

who is that directed to

**Comment by Mikolaj** [comment]
Apologies, to you. but now that I think about it, you may not have the authorization for merge. Is that it? And I don't have the authorization in this repo to give you the authorization. :)

**Comment by Mikolaj** [comment]
So let me just merge. Thank you!

**Pull request merged**
