### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by askeblad**
hackage-security-HTTP/src/Hackage/Security/Client/Repository/HttpLib/HTTP.hs
hackage-security/src/Hackage/Security/Client.hs
hackage-security/src/Hackage/Security/Client/Formats.hs
hackage-security/src/Hackage/Security/TUF/Header.hs
hackage-security/src/Hackage/Security/TUF/Layout/Cache.hs
hackage-security/src/Hackage/Security/TUF/Patterns.hs

<hr>

hackage-security/src/Hackage/Security/Key.hs

```
-- NOTE: The FromJSON and ToJSON instances for KeyId are ntentially omitted. Use
-- writeKeyAsId instead.
```

another typo as `ntentially` for someone else to correct in another PR

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
Thanks a lot.

**Comment by Mikolaj** [comment]
CI failed due to https://github.com/haskell/hackage-security/issues/270, but not because there's anything wrong in this PR. Merging.

**Comment by askeblad** [comment]
> another typo as `ntentially` for someone else to correct in another PR

hackage-security/src/Hackage/Security/Key.hs

@Mikolaj possibly `intentionally`

**Comment by Mikolaj** [comment]
> @Mikolaj possibly `intentionally`

Yes, very likely.

**Pull request merged**
