### PR TITLE
Make hackage-repo-tool build on Windows.

### LINKED ISSUE #175: hackage-repo-tool not buildable on Windows
Due to unix dependency.

### PR DESCRIPTION
**Pull request by ezyang**
Fixes #175.

Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by dcoutts** [comment]
I guess we should either make this work with the older directory versions that use old-time, or we should declare older versions of directory & ghc to be unsupported. I'd prefer the former but if it's clear no clients of this lib need this support then that would be ok.

**Comment by hvr** [comment]
With GHC 8.2 around the corner, I'd suggest to go the easier path, and declare the minimum `directory` version needed. With `cabal new-build` it's quite easy to build things that require newer versions of boot-libraries (as long as they don't depend on the `ghc` package...)

**Comment by ezyang** [comment]
I'm OK with that.

**Comment by 23Skidoo** [comment]
We should turn on AppVeyor CI as well.

**Comment by hvr** [comment]
@23Skidoo ...do you volunteer? ;->

**Comment by 23Skidoo** [comment]
Closing in favour of #206.

**Pull request closed without merging**
