### PR TITLE
tasty 1.5

### PR DESCRIPTION
**Pull request by andreasabel**
- Bump Haskell-CI GHC 9.4.5 -> 9.4.7
- Allow tasty-1.5

### CODE REVIEW

**Comment by andreasabel** [comment]
Published as revision 6: https://hackage.haskell.org/package/hackage-security-0.6.2.3/revisions/

**Comment by Mikolaj** [comment]
Thank you. Yes, let's drop them. I CI failed again, so let me rerun failed tests in case it's the `unix` package bug.

**Comment by andreasabel** [comment]
CI passed, it seems.

**Comment by Mikolaj** [comment]
Yep. Must have been that unix bug.

**Comment by andreasabel** [comment]
Ok, I added a commit to drop GHC < 7.10 from `tested-with` and Haskell CI.

**Comment by andreasabel** [comment]
Shall I rebase & merge this?

**Comment by Mikolaj** [comment]
Yes, thank you. :)

**Pull request merged**
