### PR TITLE
Update hackage-security.cabal to the newest version revised on Hackage

### PR DESCRIPTION
**Pull request by Mikolaj**

### CODE REVIEW

**Comment by Mikolaj** [comment]
There are test failures, e.g., https://github.com/haskell/hackage-security/runs/4660581702

**Comment by Bodigrim** [comment]
Compilation failures on GHC 8.2 are caused by `streaming-commons`, it has been already updated. If you rerun, they'll be gone.

**Comment by Bodigrim** [comment]
Test failures are because of `aeson-1.5`, which no longer accepts unescaped control sequences:
```
    prop_aeson_canonical:            FAIL
      *** Failed! Falsified (after 8 tests and 3 shrinks):
      JSString "\n"
      Left "Error in $: Failed reading: unescaped control character" /= Right (String "\n")
      Use --quickcheck-replay=254160 to reproduce.
      Use -p '/prop_aeson_canonical/' to rerun this test only.
```

This is expected, because comments for `renderCanonicalJSON` state:
https://github.com/haskell/hackage-security/blob/3106eec3a4d69a757df2118b38f6fbbd239775f6/hackage-security/src/Text/JSON/Canonical.hs#L113-L114

I guess the test should be amended.

**Comment by Mikolaj** [comment]
Thank you so much, @Bodigrim. I will amend the tests next week and we should be fine.

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a [revision](https://hackage.haskell.org/package/hackage-security-0.6.0.1/revisions/) relaxing `template-haskell` bounds. Otherwise earlier revisions, relaxing `base`, do not help to compile with newer GHCs. Please include it into this PR.

**Comment by Mikolaj** [comment]
Hah, I already forgot what the purpose of this exercise is. ;D

**Pull request merged**
