### PR TITLE
Bump Cabal-syntax bound to let it work with cabal 3.10 and 3.11dev

### PR DESCRIPTION
**Pull request by Mikolaj**
I plan to just revise this on Hackage for both packages.

### CODE REVIEW

**Comment by andreasabel** [comment]
CI used `Cabal-syntax 3.8.1.0` https://github.com/haskell/hackage-security/pull/290/checks#step:15:818:
> PkgId (PkgName "hackage-security") (Ver [0,6,2,3])
> CompNameTest "TestSuite"
>    Cabal-3.8.1.0

I tested these packages locally with GHC 9.6.1 alpha3 without problem.  So maybe this `Cabal-syntax` bump could be combined with a bump to GHC 9.6, to get CI to pick up at least 3.9.0.0...  I started on this.

**Comment by Mikolaj** [comment]
Yes, that would be great. And let's not forget to revise this on Hackage (at least the essential parts).

**Comment by andreasabel** [comment]
> And let's not forget to revise this on Hackage (at least the essential parts).

Did that: https://github.com/haskell/hackage-security/pull/291#issuecomment-1436711187

**Comment by Mikolaj** [comment]
Thank you so much. Closing as superseded by https://github.com/haskell/hackage-security/pull/291.

**Pull request closed without merging**
